# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCheckOut():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path="C:/Users\Public/chromedriver_win32/chromedriver.exe")
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_checkOut(self):
    self.driver.get("http://localhost/OnlinePizzaDelivery-main/OnlinePizzaDelivery-main/OnlinePizzaDelivery/viewCart.php/OnlinePizzaDelivery-main/OnlinePizzaDelivery-main/OnlinePizzaDelivery/viewCart.php")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.ID, "address").send_keys("hometqt")
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #phone").send_keys("1111111111")
    self.driver.find_element(By.ID, "zipcode").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer").click()
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.ID, "zipcode").send_keys("700000")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group #password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group #password").send_keys()
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group #password").send_keys("1234567")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #phone").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #phone").send_keys("11111abc")
    self.driver.find_element(By.ID, "zipcode").click()
    self.driver.find_element(By.ID, "zipcode").send_keys("dsds")
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #phone").send_keys("1111111111")
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group #password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group #password").send_keys("12345674343")
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.ID, "zipcode").click()
    self.driver.find_element(By.ID, "zipcode").send_keys("700000")
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group #password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group #password").send_keys("1234567")
    self.driver.find_element(By.NAME, "checkout").click()
  
