# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdjustItem():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path="C:/Users\Public/chromedriver_win32/chromedriver.exe")
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adjustItem2(self):
    self.driver.get("http://localhost/OnlinePizzaDelivery-main/OnlinePizzaDelivery-main/OnlinePizzaDelivery/viewProfile.php/OnlinePizzaDelivery-main/OnlinePizzaDelivery-main/OnlinePizzaDelivery/viewCart.php")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.NAME, "quantity").click()
    self.driver.find_element(By.NAME, "quantity").send_keys("9999")
    self.driver.find_element(By.NAME, "quantity").send_keys("abc1")
  
  def test_removeItem(self):
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .btn").click()
  
  def test_removeAll(self):
    self.driver.find_element(By.NAME, "removeAllItem").click()
  
